### ISSUE TITLE
Expose `generateScopeName` as a configuration option

### ISSUE THREAD

**Issue by nickpresta** [Shopify/loom#278]
## Overview

As part of converting [`polaris-viz` to loom](https://github.com/Shopify/polaris-viz/pull/581), I want to maintain the `generateScopeName` behavior on our styling. [`polaris-react`](https://github.com/Shopify/polaris-react/blob/483e1cf48e36cb2ba383742305c4a57f79cf8f2b/loom.config.ts#L159-L173) and [current `polaris-viz`](https://github.com/Shopify/polaris-viz/blob/77068a889b739da467723d0c1b6600052c389b26/config/rollup/plugins/styles.js#L36) both do this by way of configuring the style compilation process and by copying a lengthy file ([pv](https://github.com/Shopify/polaris-viz/blob/77068a889b739da467723d0c1b6600052c389b26/config/rollup/namespaced-classname.js), [pr](https://github.com/Shopify/polaris-react/blob/483e1cf48e36cb2ba383742305c4a57f79cf8f2b/config/rollup/namespaced-classname.js)).

### Consumer Expectation

This seems like reasonable behavior to include in `loom` via an option of some sort -- either a boolean to enable/disable this behavior (possibly with a `classnamePrefix` companion option) or baking this into `loom` as an opinion.

Similarly to how `graphql` is an option to [`rollupConfig`](https://github.com/Shopify/loom/blob/3334dc373ab6588d1c75ccc260e18128d5e7d69a/packages/loom-plugin-build-library-extended/src/plugin-rollup-config.ts#L16), I would like an option there for turning on this behaviour (if it has to be made optional).

## Type

- [x] New feature

## Motivation

> What inspired this feature request? What problems were you facing?

The current way that it looks like I need to workaround this is by overriding the existing `styles` plugin included via [`@shopify/loom-plugin-build-library-extended`](https://github.com/Shopify/loom/blob/3334dc373ab6588d1c75ccc260e18128d5e7d69a/packages/loom-plugin-build-library-extended/src/plugin-rollup-config.ts#L23-L32) just so I can set the `generateScopeName` key.

As linked in the initial description, there is a lot of code copied into a project that ways to opt into this behavior. 

Here's an example:

```typescript
export function rollupAdjustPluginPlugin() {
  return createProjectBuildPlugin('PolarisVizRollupBuildPlugin', ({hooks}) => {
    hooks.target.hook(({hooks, target}) => {
      hooks.configure.hook((configuration) => {
        configuration.rollupPlugins?.hook((rollupPlugins) => {
          const stylesConfig = target.options.rollupEsnext
            ? {
                mode: 'esnext',
                modules: {
                  generateScopedName: generateScopedName({includeHash: true}),
                },
                plugins: [postcssShopify],
              }
            : {
                mode: 'standalone',
                output: 'styles.css',
                modules: {
                  generateScopedName: generateScopedName({includeHash: false}),
                },
                plugins: [postcssShopify],
              };
          const plugins = rollupPlugins.filter(
            (plugin) => plugin && plugin.name !== 'styles',
          );
          return [
            ...plugins,
            styles(stylesConfig),
          ];
        });
      });
    });
  });
}
```

### Area

I added labels that I thought were relevant, without creating brand new labels. I added the `documentation` label was mainly because it may be possible to do this in an easier way that I'm not understanding.

### Scope

This is related to `@shopify/loom-plugin-build-library-extended` but there is no label for it (yet).

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by BPScott** [comment]
ehehehe, I had a feeling this might have have been coming. I wanted to have minimal options for initial launch, as it means a smaller surface area we need to maintain. I didn't really want to support whole options blobs.

You mention you want to maintain the generateScopeName behavior on your styling. May I ask why this is important?

Currently use the [default classname generation](https://github.com/madyankin/postcss-modules/blob/master/src/generateScopedName.js) which converts a class like `.First` to `._First_1gjmh_1` - where `1gjmh` is a hash of the css file's contents, and `1` is the line number that the class was found on. This behaviour is the same for the default and esnext builds. This is super minimal, and is pretty obtuse to discourage people writing their own CSS styles that hang off the classnames used by your library.


Meanwhile the [`polaris-react` style of classname generation](https://github.com/Shopify/polaris-react/blob/main/config/rollup/namespaced-classname.js), which you seem to have copied in polaris-viz, builds out classnames based upon their current folder path, and optionally adds a hash in the esnext build. In a `components/Avatar/Avatar.scss`, This converts `.Avatar` to `.Polaris-Avatar` (/ `.Polaris-Avatar_z763p` in esnext), `.sizeSmall` to `.Polaris-Avatar--sizeSmall`, etc. See https://unpkg.com/browse/@shopify/polaris@7.0.0/build/esm/styles.css for further examples.

This is more verbose than the default behaviour but it is designed so that people can author pure HTML using the classnames provided by polaris. This is a neat ideal but in reality this is actually very hard to do - there is no guarantee that the html structure of a component will remain consistent between minor/patch versions - as the react component is considered the public API, not the HTML output - people freely adjust the internal html structure of components without considering them breaking changes - this makes it basically impossible to upgrade polaris if you use it in this way as you would need to audit every usage of a component's classes to ensure the html structure / classnames don't change. As such I consider this an anti-feature and would like to see it killed. https://blog.shopify.io/@sam.rose/what-s-next-for-styling-8c722daf talks about obsfucation being an explict design goal of future work which is directly at odds with human-writable classes.
These human-writable classes also imply that it would be easy to go write your own css to modify the behaviour of the elements provided by polaris-vis. Which I want to discourage, as that also breaks the contract of "updating in minor versions won't break anything".

Does polaris-vis need these class names to be human-writable? I would really hope that it does not, as in my opinions it just encourages problems?

**Comment by nickpresta** [comment]
Consider this request revoked 😃
